"""
Module  : manage_books.py
Description: Implementation of the "Manage Books" use case
             - Librarian can: add new books, edit book information, delete books
             - The system supports creating Book Categories for classification
             - Only Librarians are authorized to perform actions (Special Requirement 6.3)
             - The system automatically updates quantity & status (Postcondition 6.5)

Author  : (Generated by Claude based on use case specification provided by the user)
"""

from __future__ import annotations
from dataclasses import dataclass, field
from typing import Dict, List, Optional
from enum import Enum
from datetime import datetime
import itertools


# 1. ENUMS & EXCEPTIONS

class BookStatus(str, Enum):
    """Book availability status, automatically maintained by the system based on Quantity."""
    IN_STOCK = "In Stock"
    OUT_OF_STOCK = "Out of Stock"


class ManageBookError(Exception):
    """Base business-logic exception for the Manage Books use case."""
    pass


class UnauthorizedAccessError(ManageBookError):
    """Raised when the actor is not a Librarian (Section 6.3 - Special Requirements)."""
    pass


class CategoryNotFoundError(ManageBookError):
    """Raised when the requested Category does not exist in the system."""
    pass


class CategoryAlreadyExistsError(ManageBookError):
    """Raised when attempting to create a Category that already exists."""
    pass


class BookNotFoundError(ManageBookError):
    """Raised when no Book matches the given id."""
    pass


class ValidationError(ManageBookError):
    """Raised when input data fails validation rules."""
    pass


# 2. DOMAIN MODELS

@dataclass
class BookCategory:
    """Represents a book category (genre / subject classification)."""
    category_id: int
    name: str

    def __str__(self) -> str:
        return f"[{self.category_id}] {self.name}"


@dataclass
class Book:
    """Represents a single book title held in the library catalog."""
    book_id: int
    title: str
    author: str
    category: BookCategory
    publisher: str
    quantity: int
    status: BookStatus = field(init=False)
    created_at: datetime = field(default_factory=datetime.now)
    updated_at: datetime = field(default_factory=datetime.now)

    def __post_init__(self):
        # Derive initial status from the supplied quantity
        self.status = self._compute_status(self.quantity)

    @staticmethod
    def _compute_status(quantity: int) -> BookStatus:
        """Return IN_STOCK when at least one copy is available, OUT_OF_STOCK otherwise."""
        return BookStatus.IN_STOCK if quantity > 0 else BookStatus.OUT_OF_STOCK

    def refresh_status(self):
        """
        Recompute and persist the book's status based on its current quantity.
        Called after every mutation to satisfy Postcondition 6.5:
        'The book information, quantity, and status are updated successfully.'
        """
        self.status = self._compute_status(self.quantity)
        self.updated_at = datetime.now()

    def __str__(self) -> str:
        return (f"[{self.book_id}] '{self.title}' - {self.author} | "
                f"Category: {self.category.name} | Publisher: {self.publisher} | "
                f"Qty: {self.quantity} | Status: {self.status.value}")


@dataclass
class Librarian:
    """
    Represents a library staff member with the Librarian role.
    Only users carrying this role are permitted to execute the Manage Books
    use case (Section 6.3 - Special Requirements).
    """
    user_id: int
    name: str
    role: str = "Librarian"

    def is_librarian(self) -> bool:
        """Return True if this user holds the Librarian role."""
        return self.role == "Librarian"


# 3. CATALOG — CORE BUSINESS LOGIC CLASS

class LibraryCatalog:
    """
    Central class that implements the Manage Books use case.

    Exposes all business operations:
      - add_category()          : create a new book category
      - add_book()              : add a new book (category must already exist)
      - edit_book()             : update book information
      - delete_book()           : remove a book (requires explicit confirmation)
      - list_books()            : retrieve all books
      - list_categories()       : retrieve all categories
      - find_books_by_category(): filter books by category
    """

    def __init__(self):
        self._categories: Dict[int, BookCategory] = {}
        self._books: Dict[int, Book] = {}
        self._category_id_counter = itertools.count(1)
        self._book_id_counter = itertools.count(1)

    # Helper: authorization check (Section 6.3 - Special Requirements)
    @staticmethod
    def _check_authorization(librarian: Librarian):
        """
        Verify that the actor is a Librarian before any operation.
        Raises UnauthorizedAccessError if the check fails.
        """
        if librarian is None or not librarian.is_librarian():
            raise UnauthorizedAccessError(
                "Only Librarians are authorized to perform the Manage Books function."
            )

    # 3.1 Category Management  (flow step: "Add Book Category")
    def add_category(self, librarian: Librarian, name: str) -> BookCategory:
        """
        Create a new book category.

        Corresponds to the flow step:
        'Librarian selects Add Book Category and enters the new category information.
         The system saves the category and updates the category list.'
        """
        self._check_authorization(librarian)

        if not name or not name.strip():
            raise ValidationError("Category name must not be empty.")

        name = name.strip()
        if self._find_category_by_name(name):
            raise CategoryAlreadyExistsError(f"Category '{name}' already exists.")

        category = BookCategory(category_id=next(self._category_id_counter), name=name)
        self._categories[category.category_id] = category
        return category

    def _find_category_by_name(self, name: str) -> Optional[BookCategory]:
        """Case-insensitive lookup of a category by name. Returns None if not found."""
        for c in self._categories.values():
            if c.name.lower() == name.lower():
                return c
        return None

    def get_category(self, category_id: int) -> BookCategory:
        """Retrieve a category by its id. Raises CategoryNotFoundError if absent."""
        category = self._categories.get(category_id)
        if category is None:
            raise CategoryNotFoundError(f"Category id={category_id} does not exist.")
        return category

    def list_categories(self) -> List[BookCategory]:
        """Return all registered categories."""
        return list(self._categories.values())

    # 3.2 Add New Book  (Main Flow)
    def add_book(
        self,
        librarian: Librarian,
        title: str,
        author: str,
        category_id: int,
        publisher: str,
        quantity: int,
    ) -> Book:
        """
        Add a new book to the catalog.

        Per the use case specification: if the desired category does not yet exist,
        the Librarian must call add_category() first. This method will NOT create
        a category implicitly — it raises CategoryNotFoundError instead, guiding
        the Librarian through the correct flow (step 4 of 6.2.1).
        """
        self._check_authorization(librarian)
        self._validate_book_fields(title, author, publisher, quantity)

        # Step: "If the book category does not exist, the Librarian selects
        # 'Add Book Category'." — the category must be registered before adding a book.
        category = self._categories.get(category_id)
        if category is None:
            raise CategoryNotFoundError(
                f"Category id={category_id} does not exist. "
                f"Please call add_category() to register the category before adding a book."
            )

        book = Book(
            book_id=next(self._book_id_counter),
            title=title.strip(),
            author=author.strip(),
            category=category,
            publisher=publisher.strip(),
            quantity=quantity,
        )
        self._books[book.book_id] = book
        return book

    @staticmethod
    def _validate_book_fields(title: str, author: str, publisher: str, quantity: int):
        """Validate required book fields before insertion or update."""
        if not title or not title.strip():
            raise ValidationError("Title must not be empty.")
        if not author or not author.strip():
            raise ValidationError("Author must not be empty.")
        if not publisher or not publisher.strip():
            raise ValidationError("Publisher must not be empty.")
        if not isinstance(quantity, int) or quantity < 0:
            raise ValidationError("Quantity must be a non-negative integer.")

    # 3.3 Edit Book Information
    def edit_book(
        self,
        librarian: Librarian,
        book_id: int,
        title: Optional[str] = None,
        author: Optional[str] = None,
        category_id: Optional[int] = None,
        publisher: Optional[str] = None,
        quantity: Optional[int] = None,
    ) -> Book:
        """
        Update one or more fields of an existing book.

        Only pass the fields that need to change; any argument left as None
        will retain its current value.
        """
        self._check_authorization(librarian)
        book = self.get_book(book_id)

        if title is not None:
            if not title.strip():
                raise ValidationError("Title must not be empty.")
            book.title = title.strip()

        if author is not None:
            if not author.strip():
                raise ValidationError("Author must not be empty.")
            book.author = author.strip()

        if publisher is not None:
            if not publisher.strip():
                raise ValidationError("Publisher must not be empty.")
            book.publisher = publisher.strip()

        if category_id is not None:
            # Raises CategoryNotFoundError if the target category does not exist
            book.category = self.get_category(category_id)

        if quantity is not None:
            if not isinstance(quantity, int) or quantity < 0:
                raise ValidationError("Quantity must be a non-negative integer.")
            book.quantity = quantity

        # Postcondition 6.5: "the quantity and status of the book are updated successfully"
        book.refresh_status()
        return book

    # 3.4 Delete Book  (requires explicit confirmation)
    def delete_book(self, librarian: Librarian, book_id: int, confirm: bool = False) -> bool:
        """
        Remove a book from the catalog.

        The `confirm` parameter models the use case step:
        'The Librarian selects Delete Book and confirms the deletion of a book.'

        - confirm=False : deletion is aborted (user cancelled); returns False.
        - confirm=True  : book is permanently removed; returns True.
        """
        self._check_authorization(librarian)

        # Raises BookNotFoundError if the book does not exist
        self.get_book(book_id)

        if not confirm:
            # User has not confirmed — do not delete, return False
            return False

        del self._books[book_id]
        # Postcondition 6.5: catalog quantity and status are implicitly updated
        # because the book record no longer exists in the system.
        return True

    # 3.5 Query Helpers
    def get_book(self, book_id: int) -> Book:
        """Retrieve a single book by its id. Raises BookNotFoundError if absent."""
        book = self._books.get(book_id)
        if book is None:
            raise BookNotFoundError(f"Book id={book_id} does not exist.")
        return book

    def list_books(self) -> List[Book]:
        """Return all books currently held in the catalog."""
        return list(self._books.values())

    def find_books_by_category(self, category_id: int) -> List[Book]:
        """Return all books that belong to the specified category."""
        category = self.get_category(category_id)  # validate the category first
        return [
            b for b in self._books.values()
            if b.category.category_id == category.category_id
        ]


# 4. DEMO — ILLUSTRATIVE USAGE (run this file directly to execute)

def _demo():
    catalog = LibraryCatalog()

    librarian = Librarian(user_id=1, name="Alice")
    stranger = Librarian(user_id=2, name="Bob", role="Member")  # not a librarian

    print("=== 1. Attempt to add a category without Librarian role ===")
    try:
        catalog.add_category(stranger, "Science")
    except UnauthorizedAccessError as e:
        print("Error (expected):", e)

    print("\n=== 2. Librarian creates new categories ===")
    cat_tech = catalog.add_category(librarian, "Information Technology")
    cat_lit = catalog.add_category(librarian, "Literature")
    print("Category list:", [str(c) for c in catalog.list_categories()])

    print("\n=== 3. Add new books ===")
    book1 = catalog.add_book(
        librarian,
        title="Clean Code",
        author="Robert C. Martin",
        category_id=cat_tech.category_id,
        publisher="Prentice Hall",
        quantity=5,
    )
    print("Added:", book1)

    book2 = catalog.add_book(
        librarian,
        title="The Old Man and the Sea",
        author="Ernest Hemingway",
        category_id=cat_lit.category_id,
        publisher="Scribner",
        quantity=0,
    )
    print("Added:", book2)

    print("\n=== 4. Attempt to add a book with a non-existent category ===")
    try:
        catalog.add_book(
            librarian,
            title="Unknown Book",
            author="Unknown Author",
            category_id=999,
            publisher="Unknown Publisher",
            quantity=3,
        )
    except CategoryNotFoundError as e:
        print("Error (expected):", e)

    print("\n=== 5. Edit book information (update quantity) ===")
    catalog.edit_book(librarian, book2.book_id, quantity=10)
    print("After edit:", catalog.get_book(book2.book_id))

    print("\n=== 6. Delete book WITHOUT confirmation ===")
    result = catalog.delete_book(librarian, book1.book_id, confirm=False)
    print("Delete result (no confirm):", result)
    print("Book still exists:", catalog.get_book(book1.book_id))

    print("\n=== 7. Delete book WITH confirmation ===")
    result = catalog.delete_book(librarian, book1.book_id, confirm=True)
    print("Delete result (confirmed):", result)

    print("\n=== 8. Remaining books in catalog ===")
    for b in catalog.list_books():
        print(" -", b)


if __name__ == "__main__":
    _demo()